server:
  port: 8080
spring:
  application:
    name: selldok-toy
  datasource:
    #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driver-class-name: org.h2.Driver
#    url: jdbc:log4jdbc:h2:mem:testdb
    url: jdbc:h2:tcp://localhost/~/wanted
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-db
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
  mvc:
    view:
      suffix: .html
  thymeleaf:
    cache: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 5
  servlet:
    multipart:
      location: C:/Users/ggs/Documents/workspaces/CLONE-PROJECT/src/main/resources/static/upload/
      maxFileSize: 10MB
      maxRequestSize: 10MB

#  webflux:
#    static-path-pattern: "/resources/**"

mybatis:
  type-aliases-package: com.selldok.toy.mapper
  mapper-locations: mybatis/mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  level:
    jdbc.sqlonly: DEBUG
    org.springframework.web: DEBUG
    com.zaxxer.hikari.HikariDataSource: ERROR

---

spring:
  profiles: dev_env_dskim
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9092/~/util/h2/db/wanted;INIT=CREATE SCHEMA IF NOT EXISTS wanted\;SET SCHEMA wanted  
  jpa:
    hibernate:
      ddl-auto: update